sudo: required
services:
  - docker

before_install:
  - docker build -t  gaurav-bhardwaj/docker-react -f Dockerfile.dev .

script:
  - travis_wait 15 docker run -e CI=true gaurav-bhardwaj/docker-react npm run test -- --coverage

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-204750130783"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key:
  #   secure: "$AWS_SECRET_KEY"