sudo: required
services:
  - docker

before_install:
  - docker build -t  gaurav-bhardwaj/docker-react -f Dockerfile.dev .

script:
  - docker run gaurav-bhardwaj/docker-react npm run test -- --coverage